import type { Product, Category, Review } from './types';
import { PlaceHolderImages } from './placeholder-images';

const findImage = (id: string) => PlaceHolderImages.find(img => img.id === id)?.imageUrl || '';

export const categories: Category[] = [
  {
    categoryId: '1',
    name: 'Electronics',
    imageURL: findImage('category-electronics'),
    isActive: true,
    order: 1,
  },
  {
    categoryId: '2',
    name: 'Fashion',
    imageURL: findImage('category-fashion'),
    isActive: true,
    order: 2,
  },
  {
    categoryId: '3',
    name: 'Home Goods',
    imageURL: findImage('category-homegoods'),
    isActive: true,
    order: 3,
  },
  {
    categoryId: '4',
    name: 'Books',
    imageURL: findImage('category-books'),
    isActive: true,
    order: 4,
  },
];

export const products: Product[] = [
  {
    productId: '1',
    sellerId: 'seller1',
    name: 'Modern Smartwatch',
    description: 'A sleek and modern smartwatch with all the latest features.',
    price: 299.99,
    discountedPrice: 249.99,
    currency: 'USD',
    category: 'Electronics',
    brand: 'TechGears',
    images: [findImage('product-smartwatch'), findImage('product-smartwatch'), findImage('product-smartwatch')],
    specifications: {
      'Screen Size': '1.4 inch',
      'Battery Life': '48 hours',
      'Water Resistance': '5 ATM',
    },
    stockQuantity: 50,
    sku: 'TG-SW-001',
    ratings: {
      average: 4.8,
      count: 150,
    },
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    tags: ['smartwatch', 'wearable', 'tech'],
  },
  {
    productId: '2',
    sellerId: 'seller2',
    name: 'Wireless Headphones',
    description: 'High-quality wireless headphones with noise-cancelling feature.',
    price: 199.99,
    currency: 'USD',
    category: 'Electronics',
    brand: 'AudioPhonic',
    images: [findImage('product-headphones'), findImage('product-headphones'), findImage('product-headphones')],
    specifications: {
      'Connectivity': 'Bluetooth 5.2',
      'Playtime': '30 hours',
      'Color': 'Matte Black',
    },
    stockQuantity: 100,
    sku: 'AP-HP-005',
    ratings: {
      average: 4.6,
      count: 230,
    },
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    tags: ['headphones', 'audio', 'wireless'],
  },
  {
    productId: '3',
    sellerId: 'seller3',
    name: 'Running Sneakers',
    description: 'Comfortable and stylish sneakers for your daily run.',
    price: 120.0,
    currency: 'USD',
    category: 'Fashion',
    brand: 'FastFlex',
    images: [findImage('product-sneakers'), findImage('product-sneakers'), findImage('product-sneakers')],
    specifications: {
      'Upper Material': 'Mesh',
      'Sole': 'Rubber',
      'Best for': 'Road running',
    },
    stockQuantity: 200,
    sku: 'FF-SNK-010',
    ratings: {
      average: 4.7,
      count: 320,
    },
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    tags: ['shoes', 'running', 'sportswear'],
  },
  {
    productId: '4',
    sellerId: 'seller1',
    name: 'Travel Backpack',
    description: 'A durable and spacious backpack for all your travel needs.',
    price: 89.99,
    discountedPrice: 79.99,
    currency: 'USD',
    category: 'Fashion',
    brand: 'UrbanNomad',
    images: [findImage('product-backpack'), findImage('product-backpack'), findImage('product-backpack')],
    specifications: {
      'Capacity': '35L',
      'Material': 'Water-resistant Nylon',
      'Laptop Compartment': 'Fits 15-inch laptop',
    },
    stockQuantity: 80,
    sku: 'UN-BP-002',
    ratings: {
      average: 4.9,
      count: 450,
    },
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    tags: ['backpack', 'travel', 'gear'],
  },
  {
    productId: '5',
    sellerId: 'seller2',
    name: 'DSLR Camera',
    description: 'Professional DSLR camera for stunning photography.',
    price: 899.99,
    currency: 'USD',
    category: 'Electronics',
    brand: 'PixelPerfect',
    images: [findImage('product-camera'), findImage('product-camera'), findImage('product-camera')],
    specifications: {
      'Resolution': '24.2 MP',
      'Sensor': 'APS-C CMOS',
      'ISO': '100-25600',
    },
    stockQuantity: 30,
    sku: 'PP-DSLR-101',
    ratings: {
      average: 4.8,
      count: 95,
    },
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    tags: ['camera', 'photography', 'dslr'],
  },
  {
    productId: '6',
    sellerId: 'seller4',
    name: 'Ergonomic Office Chair',
    description: 'Stay comfortable during long work hours with this ergonomic chair.',
    price: 350.0,
    currency: 'USD',
    category: 'Home Goods',
    brand: 'ComfySit',
    images: [findImage('product-chair'), findImage('product-chair'), findImage('product-chair')],
    specifications: {
      'Material': 'Mesh back, fabric seat',
      'Adjustments': 'Height, Tilt, Armrests',
      'Weight Capacity': '300 lbs',
    },
    stockQuantity: 40,
    sku: 'CS-CH-001',
    ratings: {
      average: 4.5,
      count: 110,
    },
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    tags: ['office', 'furniture', 'chair'],
  },
  {
    productId: '7',
    sellerId: 'seller4',
    name: 'Minimalist Desk Lamp',
    description: 'A stylish and minimalist desk lamp to brighten your workspace.',
    price: 65.0,
    currency: 'USD',
    category: 'Home Goods',
    brand: 'Lumina',
    images: [findImage('product-lamp'), findImage('product-lamp'), findImage('product-lamp')],
    specifications: {
      'Light Source': 'LED',
      'Power': '10W',
      'Color Temperature': '3000K-6000K',
    },
    stockQuantity: 120,
    sku: 'LM-DL-020',
    ratings: {
      average: 4.7,
      count: 180,
    },
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    tags: ['lamp', 'lighting', 'office'],
  },
  {
    productId: '8',
    sellerId: 'seller4',
    name: 'Ceramic Plant Pot',
    description: 'A beautiful ceramic pot for your indoor plants.',
    price: 25.0,
    discountedPrice: 19.99,
    currency: 'USD',
    category: 'Home Goods',
    brand: 'GreenThumb',
    images: [findImage('product-pot'), findImage('product-pot'), findImage('product-pot')],
    specifications: {
      'Material': 'Ceramic',
      'Diameter': '6 inches',
      'Drainage Hole': 'Yes',
    },
    stockQuantity: 300,
    sku: 'GT-POT-003',
    ratings: {
      average: 4.9,
      count: 250,
    },
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    tags: ['plant', 'pottery', 'decor'],
  },
];

export const reviews: Review[] = [
    {
        reviewId: '1',
        productId: '1',
        userId: 'user1',
        rating: 5,
        title: 'Absolutely love it!',
        comment: 'This smartwatch is fantastic. The battery life is amazing and it has all the features I need. Highly recommend!',
        helpfulCount: 12,
        reported: false,
        createdAt: new Date('2023-10-01'),
        updatedAt: new Date('2023-10-01'),
        user: { name: 'Jane Doe', avatar: findImage('avatar-1') }
    },
    {
        reviewId: '2',
        productId: '1',
        userId: 'user2',
        rating: 4,
        title: 'Great watch, one small issue',
        comment: "Overall a great product. The screen is bright and responsive. My only complaint is that the strap can be a bit uncomfortable at times.",
        helpfulCount: 5,
        reported: false,
        createdAt: new Date('2023-09-28'),
        updatedAt: new Date('2023-09-28'),
        user: { name: 'John Smith', avatar: findImage('avatar-2') }
    }
];
